### PR TITLE
Add a `null` rendering backend

### PR DESCRIPTION
**Pull request by Wunkolo**
This adds the null rendering backend, which just stubs all of the implementation details of the rendering backend, allowing for "headless" emulation of 3DS roms.
This also adds support for multiple rendering backends, based on an index within the user's `config.toml`.

### CODE REVIEW

**Comment by wheremyfoodat** [comment]
Sir I tried this and I can't see the Pokemans, I think you have a bug, please fix

**Comment by skylersaleh** [comment]
> Sir I tried this and I can't see the Pokemans, I think you have a bug, please fix

Wdym, its playing Pokemon Black perfectly.

**Comment by wheremyfoodat** [comment]
> 

Reshiram pic or lying

**Comment by wheremyfoodat** [comment]
CI seems to be dying to IWYU stuff (no <optional> in renderer.hpp)
Also likely best to move the renderer text name functions as static functions in the `Renderer` class.

So you'd do `Renderer::typeFromString` and it would be self-explanatory without global baggage.

**Comment by Wunkolo** [comment]
Addressed CI issues 👍

**Pull request merged**
