### PR TITLE
Resizing window on Qt

### PR DESCRIPTION
**Pull request by wheremyfoodat**

### CODE REVIEW

**Comment by wheremyfoodat** [comment]
Also fixes the menu bar overlaying part of the game (oops)

**Review by OFFTKP — APPROVED** [review]
image

**Comment by wheremyfoodat** [comment]
> image

AHAHAHAAHAHAHA WHAT

**Comment by OFFTKP** [comment]
Joe is disappointed :x:

**Comment by wheremyfoodat** [comment]
image

**Pull request merged**
