### PR TITLE
New README and new images

### PR DESCRIPTION
**Pull request by ArbestRiAgain**
Updated MK7 image for latest master and added in compatibility list link.

### CODE REVIEW

**Comment by ArbestRiAgain** [comment]
Squashed all the commits now and appeared to have accidentally force pushed again

**Comment by wheremyfoodat** [comment]
I will need to remove the Sims image because it makes the readme too big and harder to scroll on mobile
Can I get write access to the spreadsheet?

**Comment by ArbestRiAgain** [comment]
> I will need to remove the Sims image because it makes the readme too big and harder to scroll on mobile Can I get write access to the spreadsheet?

Wasn't it already deleted?

**Comment by wheremyfoodat** [comment]
Yeah I removed it in the commit above

**Pull request merged**
