### PR TITLE
Clean up smdh getting

### PR DESCRIPTION
**Pull request by OFFTKP**

### CODE REVIEW

**Comment by OFFTKP** [comment]
I need CI don't review

**Comment by wheremyfoodat** [comment]
Code is good, emulator.hpp just needs #include <span> (IWYU)

**Comment by OFFTKP** [comment]
done, ready for review

**Comment by wheremyfoodat** [comment]
Needs an smdh.clear() call in ncch.cpp below the `codeFile.clear()` and `saveData.clear()` calls

**Review by wheremyfoodat — APPROVED** [review]

**Comment by wheremyfoodat** [comment]
@OFFTKP Feel free to merge when ready

**Comment by wheremyfoodat** [comment]
I sort of meant after CI passed but
kanna-kamui-pat

**Pull request merged**
