### PR TITLE
Add /status command in http server

### PR DESCRIPTION
**Pull request by OFFTKP**

### CODE REVIEW

**Comment by wheremyfoodat** [comment]
That constructor is cursed but fuck it, ship it

**Review by wheremyfoodat — DISMISSED** [review]

**Comment by OFFTKP** [comment]
why is it cursed :rnap:, I wanted to initialize the map in the cpp file so as to not need to include services/hid in the header

**Comment by wheremyfoodat** [comment]
You made the right choice

**Comment by OFFTKP** [comment]
kissable (mergeable)

**Review by wheremyfoodat — APPROVED** [review]

**Pull request merged**
