### PR TITLE
Make CI appimages executable

### PR DESCRIPTION
**Pull request by OFFTKP**
PLEASE

### CODE REVIEW

**Comment by wheremyfoodat** [comment]
The Slowpoke Song Lyrics

[Intro]
Hold it! Hold up everyone!
Are you ready for a sing along?
Slowpoke in a reggae reggae style
Poké Poké Poké Pokémon
Come in!

[Chorus]
Slow slow slow
Ah-oo what's your story, Slowpoke?
Slow slow slow
Ah-oo what's your story, Slowpoke?

[Verse 1]
Every night, you're the one
Dreams of waking with the sun
But you sleep in 'til noon (Slowpoke)

Your pink hue
Is your color, through and through
I can see it's the real you (Slowpoke)

Your big mouth
Like a supermarket door
Open seven/twenty-four (Slowpoke)

Your sweet tail sap
Is a yummy yummy snack
We're hungry and we want more (Slowpoke)

[Pre-Chorus]
You're so slow, that
Your picture never blurs
The speedometer concurs
Slowpoke!

[Chorus]
Slow slow slow
Ah-oo what's your story, Slowpoke?
Slow slow slow
Dude, what's your deal, Slowpoke?

[Verse 2]
Lose your tail, that's all right
It'll grow back someday
That's really cool (Slowpoke)

Dopey Pokémon, the
Category they settled on
Too bad for you (Slowpoke)

What word starts with "S"
And ends with letter "E"?
It's obviously…(Sunstroke)

You fish with your tail
But you're too slow when they bite
And so they swim out of sight (Slowpoke)

[Pre-Chorus]
Your slow-motion roll has got a lot of soul
It's your cruise control
Slowpoke!

[Chorus]
Slow slow slow
Ah-oo what's your story, Slowpoke?
Slow slow slow
Ah-oo what's your story, Slowpoke?

[Verse 3]
You yawn a single time
Down comes the rain sublime
If the famous legend is true (Slowpoke)

But you've been yawning all day long
And the blue skies aren't gone
You've got some explaining to do (Slowpoke)

A Shellder bites your tail
And then you become a Slowbro
That's a dopey evolution (Slowpoke)

Everywhere you go
There are Slowpoke passing through
Maybe there's one right behind you (Slowpoke)

[Pre-Chorus]
Plodding, poky
Sluggish, tardy
So late you're early
Slowpoke!

[Chorus]
Slow slow slow
Dude, what's your deal, Slowpoke?
Slow slow slow
Ah-oo what's your story, Slowpoke?

[Verse 4]
A great big Berry fell
Bonked you on the head
But you feel no pain (Slowpoke)

Your ears curl in—there's a reason, you said
What was it again? (Slowpoke)

You just said "SLO"
Did you feel that Berry only just now?
You're really somethin' (Slowpoke)

Someday you'll be Slowbro, or maybe even Slowking
Or you'll just keep bein' (Slowpoke)

[Pre-Chorus]
Stand in a ring
Bite your buddy's tail for lunch
What a happy looking bunch
Slowpoke!

[Outro]
Slow slow slow
Ah-oo what's your story, Slowpoke?
Slow slow slow
Slowpoke

**Comment by wheremyfoodat** [comment]
Uhhhhhh

**Comment by OFFTKP** [comment]
I blame the song

**Comment by OFFTKP** [comment]
https://github.com/actions/upload-artifact#maintaining-file-permissions-and-case-sensitive-files

Thanks github

**Comment by wheremyfoodat** [comment]
Waste of a slowpoke song

**Pull request closed without merging**
