### PR TITLE
Massive speed improvement (<1 ms frame time)

### PR DESCRIPTION
**Pull request by noumidev**
This pull requests improves emulator speed by removing unnecessary code.

### CODE REVIEW

**Comment by wheremyfoodat** [comment]
Bestie how the fuck did you manage to delete every file and still get 12 merge conflicts

**Comment by PSI-Rockin** [comment]
This runs great! Get this merged ASAP

**Comment by noumidev** [comment]
> Bestie how the fuck did you manage to delete every file and still get 12 merge conflicts

idk do I look like a nerd, I can't git

**Comment by OFFTKP** [comment]
Everyone knows Git is a buggy mess of software. I think we should move to SVN in the next patch. Anyway please force merge.

**Comment by eepykami** [comment]
GBC support seems to be broken in this branch

**Comment by wheremyfoodat** [comment]
> Everyone knows Git is a buggy mess of software. I think we should move to SVN in the next patch. Anyway please force merge.

You must treat your codebase like your wife. No force, only love and understanding. Unless that is not the way you treat your wife...

**Comment by PSI-Rockin** [comment]
Why isn't this merged yet???? I need this PR NOW! Lazy devs!

**Comment by OFFTKP** [comment]
Please dont tell jokes about domestic abuse
They hit too close to home

**Comment by wheremyfoodat** [comment]
> Why isn't this merged yet???? I need this PR NOW! Lazy devs!

You have merge perms dum-dumb

**Comment by wheremyfoodat** [comment]
> Please dont tell jokes about domestic abuse They hit too close to home
May I suggest anger management courses

**Comment by KostaSaizo7** [comment]
**SPEEB**

**Comment by JaffaCat** [comment]
Someone is going to be interested in these PR's, read the comments and understand why we are all insane.

**Comment by BlurrySquire** [comment]
Is this a serious pull request?

**Comment by eepykami** [comment]
> Is this a serious pull request?

61ZkaCujGrL _AC_UF1000,1000_QL80_FMwebp_

**Comment by wheremyfoodat** [comment]
This is my favourite PR ever, @OFFTKP has some pretty serious PR competition

**Comment by JaffaCat** [comment]
Oh wait, I just noticed this PR removes all code...
How did I not pick up on that earlier?

**Comment by eepykami** [comment]
end of an era 😔

**Comment by PSI-Rockin** [comment]
A PR like this being closed is unacceptable. Someone needs to replace the project manager immediately!

**Comment by skylersaleh** [comment]
1984

**Comment by fleroviux** [comment]
i tired to comply this but when i try to run Alber.exe it not found?!?

**Comment by PSI-Rockin** [comment]
It's a sort of "theater of the mind" situation. If you use your imagination, you'll find all your favorite 3DS games running at blazingly fast speeds!

**Pull request closed without merging**
