### PR TITLE
Add shaderMode option and remove useUbershader option

### PR DESCRIPTION
**Pull request by OFFTKP**

### CODE REVIEW

**Comment by wheremyfoodat** [comment]
Adding support for unimplemented options :rgalaxy:

**Comment by OFFTKP** [comment]
image
This needs to be merged expeditiously

**Comment by wheremyfoodat** [comment]
#557 Fuming rn

**Comment by OFFTKP** [comment]
I included an easter egg in this PR to increase merging chances by 5%

**Pull request closed without merging**
