### PR TITLE
Add icon for hydra

### PR DESCRIPTION
**Pull request by wheremyfoodat**

### CODE REVIEW

**Comment by OFFTKP** [comment]
lgtm

**Comment by wheremyfoodat** [comment]
But does it work in the frontend

**Comment by wheremyfoodat** [comment]
Oh the rgba data might be endian flipped but it would still be good to know if the frontend shows something

**Comment by OFFTKP** [comment]
hmm now that I think of it perhaps requiring the definition of a global function is better. Because then this way I need to make an emulator instance with createEmulator to get the icon.

**Comment by OFFTKP** [comment]
image

**Comment by wheremyfoodat** [comment]
How do you report whether there's an icon or not with this API though

**Pull request merged**
