### PR TITLE
Add AUR badge

### PR DESCRIPTION
**Pull request by OFFTKP**
I made you a AUR package that builds master https://aur.archlinux.org/packages/panda3ds-git
You can build with
`yay -S panda3ds-git` on Archlinux

### CODE REVIEW

**Comment by wheremyfoodat** [comment]
rhappy
Isn't this missing Vulkan in dependencies

**Comment by OFFTKP** [comment]
I made it compile without Vulkan (is Vulkan preferred nowadays?)

**Comment by OFFTKP** [comment]
ok I'll change it to use Vulkan when it does

also panda3ds website when (to feature in the AUR package as well)
image

**Comment by wheremyfoodat** [comment]
> ok I'll change it to use Vulkan when it does
> 
> also panda3ds website when (to feature in the AUR package as well) image

@georgemoralis Literally owns panda3ds.net
image

**Comment by OFFTKP** [comment]
rpog

**Comment by wheremyfoodat** [comment]
image

**Comment by wheremyfoodat** [comment]
Ε να σε κανω ταγκ στο τουιτερ τωρα που θα ανεβασω οτι εχουμε AUR πακετο;

**Comment by OFFTKP** [comment]
κανε

ΥΓ Η ΚΟΚΚΙΝΗ ΑΙΛΟΥΡΟΠΟΔΗ ΑΡΚΟΥΔΑ 3DS ΕΙΝΑΙ ΕΛΛΗΝΙΚΗ

**Comment by wheremyfoodat** [comment]
ΠΡΑΓΜΑΤΙΚΑ ΕΙΝΑΙ ΕΛΛΗΝΙΚΗ

**Pull request merged**
