### PR TITLE
apk optimisation + compile both release and debug build 

### PR DESCRIPTION
**Pull request by Ishan09811**

### CODE REVIEW

**Comment by wheremyfoodat** [comment]
Uploading the release build fails 🤔

**Comment by Ishan09811** [comment]
@wheremyfoodat 
I don't know why but the release build is can't find in the directory to upload it so you can solve it ?

**Comment by wheremyfoodat** [comment]
The directory doesn't exist because the APK is unsigned, I'll look if it's possible to sign it with the default debug key

**Comment by wheremyfoodat** [comment]
Seems like the release APK now builds but won't open a real phone

**Comment by Ishan09811** [comment]
@wheremyfoodat 
it's now uploading the release apk btw thanks for the help

**Comment by wheremyfoodat** [comment]
Well yes but it doesn't open

**Comment by Ishan09811** [comment]
@wheremyfoodat 
maybe because of the debug and release small characters , maybe we need to use it in capital.

**Comment by Ishan09811** [comment]
@wheremyfoodat 
maybe it's causing because of the debug key

**Comment by wheremyfoodat** [comment]
This doesn't correctly pass the build type to CMake https://cmake.org/cmake/help/latest/manual/cmake-buildsystem.7.html#id37

**Comment by wheremyfoodat** [comment]
OK so the cmake docs say it's case sensitive but it's also case insensitive because that's very not confusing, this probably works then

**Pull request merged**
