### PR TITLE
Implement Fragment Lighting (and clipping planes)

### PR DESCRIPTION
**Pull request by skylersaleh**
Working to make our GPU more lit than it already is.

### CODE REVIEW

**Comment by skylersaleh** [comment]
This branch is now in a good enough state that it might be worth considering to merge.

**Comment by wheremyfoodat** [comment]
I will do some more work on this (optimization / fix up formatting / implement some misc missing things) and merge it to GamingProcessingUnit

**Comment by wheremyfoodat** [comment]
Updated the PR to add clipping planes too. Merging into GamingProcessingUnit once CI passes.

I will start working on more efficient GL state management to minimize CPU overhead and merge GamingProcessingUnit to master again when that's up.

**Comment by wheremyfoodat** [comment]
Also someone remind me to updating the images before merging into master because we need eye candy

**Comment by skylersaleh** [comment]
> Also someone remind me to update the images before merging into master because we need eye candy

I'm reminding you right now, 'cause CI is done. 😄

**Comment by wheremyfoodat** [comment]
> > Also someone remind me to update the images before merging into master because we need eye candy
> 
> I'm reminding you right now, 'cause CI is done. 😄

But this is not going to master yet >:(

**Comment by skylersaleh** [comment]
> > > Also someone remind me to update the images before merging into master because we need eye candy
> > 
> > 
> > I'm reminding you right now, 'cause CI is done. 😄
> 
> But this is not going to master yet >:(

But GamingProcessingUnit needs eyecandy love too :(

**Pull request merged**
