### PR TITLE
Set MacOS deployment target

### PR DESCRIPTION
**Pull request by wheremyfoodat**
Should fix App Bundle

### CODE REVIEW

**Comment by wheremyfoodat** [comment]
Can somebody test this for me

**Comment by CatGreen90** [comment]
I can confirm that the app bundle launches on macOS 11, at least.

**Comment by wheremyfoodat** [comment]
@CatGreen90 Thanks, updating CMake a bit to fix another bug

**Comment by wheremyfoodat** [comment]
OF COURSE DISCORD-RPC OVERRIDES THE MINIMUM MACOS VERSION
https://github.com/discord/discord-rpc/blob/963aa9f3e5ce81a4682c6ca3d136cddda614db33/src/CMakeLists.txt#L77

**Pull request merged**
