### PR TITLE
Adding Qt config & translation stuff

### PR DESCRIPTION
**Pull request by wheremyfoodat**
We're currently at the peak of UX (I don't have energy to make all separate windows help)
image

### CODE REVIEW

**Comment by extherian** [comment]
Is there any particular hold-up to merging this? For people who are willing to use the emulator in this early state, a configurable GUI would be a big quality of life boost.

**Comment by extherian** [comment]
On Jonian's GitHub, I only see his libretro integration branch. Does this have the config menu merged as well?

**Comment by wheremyfoodat** [comment]
No, unsure if the config branch is public, would need to ask them

**Comment by extherian** [comment]
I managed to compile Panda3DS using visual studio the other day, I understand the UI probably isn't ready yet but I would like to try and compile it for my own use anyway. I just don't see anywhere I can get clone from. I suppose if it's private there's nothing I can do.

**Comment by jonian** [comment]
Hi @wheremyfoodat and @extherian I haven't published the config branch yet as I haven't found the time to finish it. Hopefully I will be able to make a PR soon.

**Comment by extherian** [comment]
Thank you for the clarification, jonian. I look forward to be able to try out your work.

**Pull request closed without merging**
